<?php
    if ($_GET['id'] == "getReservationsDays") {
        $keyname =  ...
        $sys_id = ...
        ...
        $resultArr = $this->execAvailableReservationsDays($keyname, $sys_id);
        $this->responseAsJson($resultArr);
    } else if ($_GET['id'] == "listEnterprises") {
        $sys_id = ...
        $origins = ...
        ...
        $resultArr = $service->getListDetailsEnterprises($sys_id, $origins);
    } else if { 
        ... 
    } ...
?>